#!/usr/bin/osascript -l JavaScript

function getEnvVars(...keys) {
    return keys.map((key) => $.NSProcessInfo.processInfo.environment.objectForKey(key).js);
}

function run(argv) {
    let [cnt, lang, prefix, code] = getEnvVars("cnt", "lang", "prefix", "code");
    cnt = cnt ? parseInt(cnt) + 1 : 0;
    prefix = cnt == 1 ? argv[0].trim() : prefix;
    switch (cnt) {
        case 0:
            var jsonData = {
                response: `I'm going to register this snippet in \`${lang}.json\`. Please enter a prefix to proceed.\n\n\`\`\`\n${code}\n\`\`\``,
                variables: { cnt: cnt },
                behaviour: { response: "replace" },
            };
            break;
        case 1:
            var jsonData = {
                response: `If it looks good, press Enter to confirm.\n\n* Language : \`${lang}\`\n* Prefix : \`${prefix}\`\n\n\`\`\`${lang}\n${code}\n\`\`\``,
                variables: { cnt: cnt, prefix: prefix },
                behaviour: { response: "replace" },
            };
            break;
        case 2:
            var jsonData = {
                variables: { prefix: prefix },
                actionoutput: true,
            };
            break;
    }
    return JSON.stringify(jsonData);
}
